info:
    path: /api/exchange/info
    controller: App\Controller\InfoController::info
convert:
    path: /api/exchange/{units}/{fromCurr}/{toCurr}
    controller: App\Controller\ConvertController::convert
clearCache:
    path: /api/cache/clear
    controller: App\Controller\CacheController::clearCache
default:
    path: /{default}
    controller: App\Controller\DefaultController::default
    requirements:
        default: .+
    defaults:
        default: nothing